name: 'Issue Tasks Completed Check'
on: 
  issues:
    types: [opened, transferred, reopened, edited]
  issue_comment:

jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2alpha1
      with:
        message: "I posted a comment yay"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}